#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Auto-install composer dependencies if vendor doesn't exist (fresh clone)
if [ ! -d /var/www/html/vendor ]; then
    echo "Vendor directory not found. Running composer install..."
    cd /var/www/html && composer install --no-interaction
fi

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
